// <auto-generated />
namespace LerooooooyJeeeeeeenkins.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class dump : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dump));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031515005_dump"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
